

name = "maxflow-lean"
version = "0.1.0"
defaultTargets = ["maxflow-lean"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "master"

[[lean_lib]]
name = "MaxflowLean"

[[lean_exe]]
name = "maxflow-lean"
root = "Main"